### PR TITLE
build(webpack): prepend license banner in minified JS files

### LINKED ISSUE #552: Include license in distributed JS
It would be nice, if you could include a license (e.g. as a JavaScript comment) in the [distributed js file(s)](https://github.com/imgix/luminous/blob/main/dist/Luminous.min.js).

According to your license, I have to include the copyright notice. However, if I'm just including the minified bundle, I have to display the copyright notice somewhere else. So if its included within your dist, it would make things easier for me.

Take the [`bootstrap.min.css`](https://github.com/twbs/bootstrap/blob/main/dist/css/bootstrap.min.css)  bundle/dist as an example.

### PR DESCRIPTION
**Pull request by sherwinski**
Prepends a banner with this project's license details to each minified file generated, to the effect of:

```js
/*!
 * Luminous v2.3.3
 * Copyright 2015-2021, Zebrafish Labs
 * Licensed under BSD-2 (https://github.com/imgix/luminous/blob/main/LICENSE.md)
 */
```

Resolves #552

### CODE REVIEW

**Comment by sherwinski** [comment]
Hey @jdoubleu, pinging you here for awareness. Feel free to leave any feedback or confirm that this fix addresses the issue you raised. Thanks

**Comment by jdoubleu** [comment]
Yes, this looks good, so far.

However, as far as I understood, it only affects the js bundle. I am wondering whether the css bundle should also include this banner. Your license states:
> Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.

So I think, I would also have to include a copyright notice with the css.

For what I've seen, you're "building" your css with postcss? I've found a plugin, which does nearly the same, as the webpack plugin (see https://github.com/princed/postcss-banner). I'm not sure if it meets your requirements.

Thank you for your work!

**Comment by sherwinski** [comment]
@jdoubleu That makes sense, and thank you for finding that postcss plugin. I pushed up some changes and can confirm that locally the minified css file also has the license banner prepended to the beginning.

**Review by frederickfogerty — APPROVED** [review]
LGTM

**Pull request merged**
