### PR TITLE
feat: LuminousGallery onChange callback

### LINKED ISSUE #48: Add "onChange" parameter for LuminousGallery
Hello,

First of all, thank you for this great library.

As the title says, I do feel like there is one feature missing for the LuminousGallery, which is an "onChange" callback parameter when we navigate to the previous or next Luminous instance.

It would probably be nice if the direction was passed as a parameter to the callback as well.

Thank you very much.

### PR DESCRIPTION
**Pull request by GwendolenLynch**
## Description

Closes #48

### New Feature

- [ ] If this is a big feature with breaking changes, consider [opening an issue][issues] to discuss first. This is completely up to you, but please keep in mind that your PR might not be accepted.
- [x] Run unit tests to ensure all existing tests are still passing
- [x] Add new passing unit tests to cover the code introduced by your PR
- [x] Update the readme
- [x] Add some [steps](#steps-to-test) so we can test your cool new feature!
- [x] The PR title is in the [conventional commit](#conventional-commit-spec) format: e.g. `feat(<area>): added new way to do this cool thing #issue-number`
- [x] Add your info to the [contributors](#packagejson-contributors) array in package.json!

### CODE REVIEW

**Review by frederickfogerty — CHANGES_REQUESTED** [review]
LGTM overall to me, and thanks for opening this. I think the only change I would ask for is for the onChange signature to be `({ imgEl }) => void`, so that we can easily add other parameters/data to the onChange event in the future? What do you think about this? If this change is made, I'm happy to merge this!

**Comment by GwendolenLynch** [comment]
Updated, and thanks for the quick feedback!

**Comment by frederickfogerty** [comment]
@GwendolenLynch sorry for the confusion, but I more meant this on the client-side, so the user-facing API is `({ imgEl }) => void`.

i.e. this method becomes:
```js
  onChange({ imgEl }) {
    const onChange = this.settings.onChange;
    if (onChange && typeof onChange === "function") {
      onChange({ imgEl }); // <-- here is the change
    }
  }
```

**Comment by GwendolenLynch** [comment]
Oops, I wasn't paying enough attention. Updated … again. :smiley_cat:

**Review by frederickfogerty — APPROVED** [review]
Looks great, thanks @GwendolenLynch!

**Review by frederickfogerty — APPROVED** [review]
Cloned this down and the tests passed, LGTM

**Comment by frederickfogerty** [comment]
I merged this, but looks like we are having some build trouble on `main`, so it may be a little while before your PR is released

**Pull request merged**
