### PR TITLE
chore: use yarn

### PR DESCRIPTION
**Pull request by DanielRuf**

### CODE REVIEW

**Comment by frederickfogerty** [comment]
Hey @DanielRuf what's the motivation behind this? I've used a lot in the past, but what advantage does it offer in the CI context?

Since most of our consumers are probably using `npm`, and as `npm` is still considered the standard, I think we need a very good reason to stop using it for CI, for which the purpose is to ensure it is working for our consumers.

**Comment by DanielRuf** [comment]
yarn is another solution and alternative to npm and often (a bit) faster.

This PR is meant to evaluate yarn and the yarn cache for luminous.

I'll check if and how much it would benefit this project.

**Comment by DanielRuf** [comment]
yarn is slower in our case.

**Comment by frederickfogerty** [comment]
Thanks for checking back in here @DanielRuf 🙌🏻

**Pull request closed without merging**
